services:
  - type: web
    name: bbl-tracker
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn bbl_tracker:app --bind 0.0.0.0:10000"
    autoDeploy: true
