services:
  - type: web
    name: bbl-tracker
    env: python
    pythonVersion: 3.10.14
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn app:app
    autodetectPoetry: false
